[workspace]
members = [
    "crates/too_backend",
    "crates/too_crossterm",
    "crates/too_immediate",
    "crates/too_math",
    "crates/too_overlay",
    "crates/too_renderer",
    "crates/too_runner",
    "crates/too_view"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
description = "too - a tui framework"
license = "MIT OR Apache-2.0"
authors = [ "museun <museun@users.noreply.github.com>" ]
documentation = "https://docs.rs/too"
repository = "https://github.com/museun/too"
readme = "README.md"

[workspace.dependencies]
too_backend = { path = "crates/too_backend", version = "0.1.0" }
too_crossterm = { path = "crates/too_crossterm", version = "0.1.0" }
too_math = { path = "crates/too_math", version = "0.1.0" }
too_overlay = { path = "crates/too_overlay", version = "0.1.0" }
too_renderer = { path = "crates/too_renderer", version = "0.1.0" }
too_runner = { path = "crates/too_runner", version = "0.1.0" }
