[package]
name = "too_renderer"
edition = "2021"
license.workspace = true
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
repository.workspace = true

[dependencies]
too_math.workspace = true
too_events.workspace = true
