[package]
name = "too_view"
version = "0.1.0"
edition = "2021"

[dependencies]
slotmap = "1.0.7"
too_renderer.workspace = true
too_events.workspace = true
too_math.workspace = true
too_shapes.workspace = true
too_runner.workspace = true

[dev-dependencies]
too_crossterm.workspace = true
