[package]
name = "too_view"
edition = "2021"
license.workspace = true
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
repository.workspace = true

[dependencies]
slotmap = "1.0.7"
too_renderer.workspace = true
too_events.workspace = true
too_math.workspace = true
too_shapes.workspace = true
too_runner.workspace = true

[dev-dependencies]
too_crossterm.workspace = true
